language: ruby

rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"
  - "jruby-19mode"
  - "rbx"

gemfile:
  - "gemfiles/capistrano2.gemfile"
  - "gemfiles/capistrano3.gemfile"
  - "gemfiles/no_dependencies.gemfile"
  - "gemfiles/rails-3.0.gemfile"
  - "gemfiles/rails-3.1.gemfile"
  - "gemfiles/rails-3.2.gemfile"
  - "gemfiles/rails-4.0.gemfile"
  - "gemfiles/rails-4.1.gemfile"
  - "gemfiles/sinatra.gemfile"

matrix:
  allow_failures:
    - rvm: "rbx"

env:
  global: "RAILS_ENV=test"

script: "bundle exec rspec"
