sudo: false

branches:
  only:
    - "master"
    - "develop"

language: ruby
cache:
  directories:
    - vendor/bundle

rvm:
  - "2.0.0"
  - "2.3.8"
  - "2.4.5"
  - "2.5.3"
  - "2.6.0"
  - "jruby-19mode"

gemfile:
  - "gemfiles/capistrano2.gemfile"
  - "gemfiles/capistrano3.gemfile"
  - "gemfiles/no_dependencies.gemfile"
  - "gemfiles/padrino.gemfile"
  - "gemfiles/rails-3.2.gemfile"
  - "gemfiles/rails-4.0.gemfile"
  - "gemfiles/rails-4.1.gemfile"
  - "gemfiles/rails-4.2.gemfile"
  - "gemfiles/rails-5.0.gemfile"
  - "gemfiles/rails-5.1.gemfile"
  - "gemfiles/resque.gemfile"
  - "gemfiles/sequel.gemfile"
  - "gemfiles/sequel-435.gemfile"
  - "gemfiles/sinatra.gemfile"
  - "gemfiles/grape.gemfile"
  - "gemfiles/webmachine.gemfile"
  - "gemfiles/que.gemfile"

matrix:
  fast_finish: true
  include:
    - rvm: "2.1.8"
      gemfile: "gemfiles/no_dependencies.gemfile"
    - rvm: "2.2.4"
      gemfile: "gemfiles/no_dependencies.gemfile"
    - rvm: "2.5.3"
      gemfile: "gemfiles/no_dependencies.gemfile"
      script: "bundle exec rubocop"
  exclude:
    # Rails 5 doesn't support Ruby < 2.2
    - rvm: "2.0.0"
      gemfile: "gemfiles/rails-5.0.gemfile"
    - rvm: "2.0.0"
      gemfile: "gemfiles/rails-5.1.gemfile"
    - rvm: "2.5.3"
      gemfile: "gemfiles/rails-4.0.gemfile"
    - rvm: "2.5.3"
      gemfile: "gemfiles/rails-4.1.gemfile"
    - rvm: "2.6.0"
      gemfile: "gemfiles/rails-4.0.gemfile"
    - rvm: "2.6.0"
      gemfile: "gemfiles/rails-4.1.gemfile"

  allow_failures:
    - rvm: "2.4.5"
      gemfile: "gemfiles/rails-4.0.gemfile"
    - rvm: "2.4.5"
      gemfile: "gemfiles/rails-4.1.gemfile"

env:
  global:
    - "RUNNING_IN_CI=true"
    - "RAILS_ENV=test"
    - "JRUBY_OPTS=''" # Workaround https://github.com/travis-ci/travis-ci/issues/6471

before_install:
  - "gem update --system 2.7.8"
  - "gem install bundler --version 1.17.3"
before_script:
  - "bundle exec rake extension:install"
after_failure:
  - "find . -name ext/install.log -exec cat {} \\;"
  - "find . -name ext/mkmf.log -exec cat {} \\;"

script: "bundle exec rake test"
