sudo: false

language: ruby

rvm:
  - "2.0.0"
  - "2.1.8"
  - "2.2.4"
  - "2.3.0"
  - "jruby-19mode"

gemfile:
  - "gemfiles/capistrano2.gemfile"
  - "gemfiles/capistrano3.gemfile"
  - "gemfiles/no_dependencies.gemfile"
  - "gemfiles/padrino.gemfile"
  - "gemfiles/rails-3.2.gemfile"
  - "gemfiles/rails-4.0.gemfile"
  - "gemfiles/rails-4.1.gemfile"
  - "gemfiles/rails-4.2.gemfile"
  - "gemfiles/rails-5.0.gemfile"
  - "gemfiles/resque.gemfile"
  - "gemfiles/sequel.gemfile"
  - "gemfiles/sequel-435.gemfile"
  - "gemfiles/sinatra.gemfile"
  - "gemfiles/grape.gemfile"

matrix:
  exclude:
    - rvm: "2.0.0"
      gemfile: "gemfiles/rails-5.0.gemfile"
    - rvm: "2.1.8"
      gemfile: "gemfiles/rails-5.0.gemfile"
    - rvm: "jruby-19mode"
      gemfile: "gemfiles/rails-5.0.gemfile"
  allow_failures:
    - rvm: "jruby-19mode"

env:
  global: "RAILS_ENV=test"

script: "bundle exec rake travis"
