name: Ruby

on:
  push:
    branches:
      - master
      - develop
  pull_request: {}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
        ruby:
          - "1.9.3"
          - "2.6.4"
        gem:
          - "no_dependencies"
          - "sinatra"

    name: Ruby ${{ matrix.ruby }} - ${{ matrix.gem }} on ${{ matrix.os }} test suite
    runs-on: ${{ matrix.os }}
    container: ruby:1.9.3
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: "Install bundle"
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gem }}.gemfile
      run: |
        gem update --no-document --system
        gem install bundler --force
        bundle install --jobs 4 --retry 3
    - name: "Install extension"
      run: bundle exec rake extension:install
    - name: "RSpec"
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gem }}.gemfile
      run: bundle exec rake test
